services:
  - type: web
    name: Dblog
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd Dblog && gunicorn dblog.wsgi:application"
    repo: https://github.com/Rachamv/Dblog.git # optional
  # plan: standard # optional
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dblog
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4